# beginning

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [17]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# data loading

In [18]:
df_encoded = pd.read_excel("/content/drive/MyDrive/capstone/datasets/5_encoded.xlsx")

In [19]:
df_encoded.head()

,age,latitude,longitude,feels_like,temp_min,temp_max,air_pressure,air_humidity,wind_speed,wind_deg,...,gender_encoded_male,gender_encoded_third gender,workplace_encoded_rural,workplace_encoded_semi-urban,workplace_encoded_urban,religion_encoded_buddhist,religion_encoded_christian,religion_encoded_hindu,religion_encoded_indigenous,religion_encoded_muslim
0,NaN,23.960600,91.119089,302.86,299.15,299.15,1008.0,83.0,2.10,320.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,20.0,24.899220,91.868527,299.17,295.57,295.57,1012.0,96.0,1.39,116.0,...,1.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0
2,14.0,23.832984,89.966688,304.33,301.15,301.15,1004.0,78.0,3.60,190.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,NaN,24.850066,89.372843,303.67,299.34,299.34,1003.0,91.0,2.64,186.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,18.0,23.764386,90.389014,304.49,300.15,300.15,1004.0,83.0,1.99,154.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [20]:
df_encoded.shape

(1617, 37)

In [21]:
def missing_data_report(df):
    # Calculate the percentage of missing data for each column
    missing_percentage = df.isna().mean() * 100

    # Get the data types of each column
    data_types = df.dtypes

    # Create a DataFrame for the missing data summary including data types
    missing_data_summary = pd.DataFrame({
        'Column': missing_percentage.index,
        'Missing Percentage': missing_percentage.values,
        'Data Type': data_types.values
    })

    # Define the four groups based on missing percentage
    group_1 = missing_data_summary[missing_data_summary['Missing Percentage'] > 70][['Column', 'Missing Percentage', 'Data Type']]
    group_2 = missing_data_summary[(missing_data_summary['Missing Percentage'] > 40) & (missing_data_summary['Missing Percentage'] <= 70)][['Column', 'Missing Percentage', 'Data Type']]
    group_3 = missing_data_summary[(missing_data_summary['Missing Percentage'] > 20) & (missing_data_summary['Missing Percentage'] <= 40)][['Column', 'Missing Percentage', 'Data Type']]
    group_4 = missing_data_summary[missing_data_summary['Missing Percentage'] <= 20][['Column', 'Missing Percentage', 'Data Type']]

    # Sort each group by missing percentage in descending order (most missing to least missing)
    group_1 = group_1.sort_values(by='Missing Percentage', ascending=False).reset_index(drop=True)
    group_2 = group_2.sort_values(by='Missing Percentage', ascending=False).reset_index(drop=True)
    group_3 = group_3.sort_values(by='Missing Percentage', ascending=False).reset_index(drop=True)
    group_4 = group_4.sort_values(by='Missing Percentage', ascending=False).reset_index(drop=True)


    # Rename columns for clarity
    group_1.columns = ['Column', 'Missing %', 'Data Type']
    group_2.columns = ['Column', 'Missing %', 'Data Type']
    group_3.columns = ['Column', 'Missing %', 'Data Type']
    group_4.columns = ['Column', 'Missing %', 'Data Type']

    # Display each group one by one, from most missing to least missing
    print("Group 1: Columns with >70% missing data")
    print(group_1.to_string(index=False))
    print("\nGroup 2: Columns with >40% to ≤70% missing data")
    print(group_2.to_string(index=False))
    print("\nGroup 3: Columns with >20% to ≤40% missing data")
    print(group_3.to_string(index=False))
    print("\nGroup 4: Columns with ≤20% missing data")
    print(group_4.to_string(index=False))

In [22]:
missing_data_report(df_encoded)

Group 1: Columns with >70% missing data
Empty DataFrame
Columns: [Column, Missing %, Data Type]
Index: []

Group 2: Columns with >40% to ≤70% missing data
                     Column  Missing % Data Type
                 feels_like  53.061224   float64
               air_humidity  53.061224   float64
                   wind_deg  53.061224   float64
                 clouds_sky  53.061224   float64
       weather_main_encoded  52.999382   float64
weather_description_encoded  52.999382   float64
financial_condition_encoded  45.516388   float64

Group 3: Columns with >20% to ≤40% missing data
                      Column  Missing % Data Type
workplace_encoded_semi-urban  37.909709   float64
     workplace_encoded_urban  37.909709   float64
     workplace_encoded_rural  37.909709   float64
                air_pressure  30.426716   float64
                  wind_speed  30.179344   float64
                    temp_min  29.870130   float64
                    temp_max  29.560915   float64
      marital_status_encoded  23.933210   float64

Group 4: Columns with ≤20% missing data
                     Column  Missing % Data Type
   profession_group_encoded  18.923933   float64
             reason_encoded  16.821274   float64
                        age  12.739641   float64
               time_encoded  12.059369   float64
          age_group_encoded   7.421150   float64
                   latitude   6.493506   float64
                  longitude   6.493506   float64
             method_encoded   2.906617   float64
              suicide_month   2.411874   float64
                suicide_day   2.411874   float64
    suicide_weekday_encoded   2.411874   float64
               suicide_week   2.411874   float64
               suicide_year   2.411874   float64
  religion_encoded_buddhist   2.411874   float64
    religion_encoded_muslim   2.411874   float64
religion_encoded_indigenous   2.411874   float64
     religion_encoded_hindu   2.411874   float64
 religion_encoded_christian   2.411874   float64
           hometown_encoded   1.669759   float64
gender_encoded_third gender   0.432900   float64
      gender_encoded_female   0.432900   float64
        gender_encoded_male   0.432900   float64

In [23]:
df_encoded.columns

Index(['age', 'latitude', 'longitude', 'feels_like', 'temp_min', 'temp_max',
       'air_pressure', 'air_humidity', 'wind_speed', 'wind_deg', 'clouds_sky',
       'time_encoded', 'suicide_day', 'suicide_month', 'suicide_year',
       'suicide_week', 'age_group_encoded', 'financial_condition_encoded',
       'weather_main_encoded', 'suicide_weekday_encoded',
       'profession_group_encoded', 'hometown_encoded', 'reason_encoded',
       'method_encoded', 'weather_description_encoded',
       'marital_status_encoded', 'gender_encoded_female',
       'gender_encoded_male', 'gender_encoded_third gender',
       'workplace_encoded_rural', 'workplace_encoded_semi-urban',
       'workplace_encoded_urban', 'religion_encoded_buddhist',
       'religion_encoded_christian', 'religion_encoded_hindu',
       'religion_encoded_indigenous', 'religion_encoded_muslim'],
      dtype='object')

In [24]:
import pandas as pd

def compute_sorted_correlations(df, threshold=0.0):
    corr_matrix = df.corr()

    result = []

    for col in corr_matrix.columns:
        # Drop self-correlation
        related = corr_matrix[col].drop(labels=[col])

        # Keep only correlations above threshold (excluding exact 0)
        related_filtered = related[related.abs() > threshold]

        # Sort by absolute correlation descending
        related_sorted = related_filtered.reindex(related_filtered.abs().sort_values(ascending=False).index)

        # Format results
        related_list = [
            {'related_column': other_col, 'related_value': round(related_value, 4)}
            for other_col, related_value in related_sorted.items()
        ]

        result.append({
            'column_name': col,
            'related_columns': related_list
        })

    return result

In [25]:
correlation_dict = compute_sorted_correlations(df_encoded)

from pprint import pprint
display(correlation_dict[:2])  # preview first 2 entries

[{'column_name': 'age',
  'related_columns': [{'related_column': 'age_group_encoded',
    'related_value': 0.8346},
   {'related_column': 'profession_group_encoded', 'related_value': -0.6141},
   {'related_column': 'gender_encoded_male', 'related_value': 0.2746},
   {'related_column': 'gender_encoded_female', 'related_value': -0.2718},
   {'related_column': 'marital_status_encoded', 'related_value': 0.1761},
   {'related_column': 'method_encoded', 'related_value': -0.1149},
   {'related_column': 'reason_encoded', 'related_value': -0.0955},
   {'related_column': 'temp_max', 'related_value': 0.0686},
   {'related_column': 'temp_min', 'related_value': 0.0662},
   {'related_column': 'workplace_encoded_rural', 'related_value': -0.0633},
   {'related_column': 'feels_like', 'related_value': 0.0549},
   {'related_column': 'clouds_sky', 'related_value': -0.0535},
   {'related_column': 'suicide_day', 'related_value': -0.0454},
   {'related_column': 'religion_encoded_muslim', 'related_value': -0.0452},
   {'related_column': 'workplace_encoded_urban', 'related_value': 0.0448},
   {'related_column': 'air_pressure', 'related_value': -0.0442},
   {'related_column': 'longitude', 'related_value': -0.0363},
   {'related_column': 'suicide_weekday_encoded', 'related_value': -0.036},
   {'related_column': 'religion_encoded_christian', 'related_value': 0.0357},
   {'related_column': 'suicide_year', 'related_value': -0.0346},
   {'related_column': 'time_encoded', 'related_value': -0.0335},
   {'related_column': 'religion_encoded_hindu', 'related_value': 0.0321},
   {'related_column': 'workplace_encoded_semi-urban', 'related_value': 0.0313},
   {'related_column': 'latitude', 'related_value': 0.0306},
   {'related_column': 'gender_encoded_third gender', 'related_value': -0.0259},
   {'related_column': 'weather_main_encoded', 'related_value': -0.0257},
   {'related_column': 'financial_condition_encoded', 'related_value': 0.0228},
   {'related_column': 'religion_encoded_indigenous', 'related_value': 0.0208},
   {'related_column': 'suicide_week', 'related_value': 0.0208},
   {'related_column': 'religion_encoded_buddhist', 'related_value': 0.0205},
   {'related_column': 'wind_speed', 'related_value': -0.0198},
   {'related_column': 'air_humidity', 'related_value': -0.0181},
   {'related_column': 'hometown_encoded', 'related_value': 0.0174},
   {'related_column': 'weather_description_encoded', 'related_value': 0.0155},
   {'related_column': 'suicide_month', 'related_value': 0.0131},
   {'related_column': 'wind_deg', 'related_value': -0.01}]},
 {'column_name': 'latitude',
  'related_columns': [{'related_column': 'longitude',
    'related_value': -0.4123},
   {'related_column': 'temp_max', 'related_value': 0.1622},
   {'related_column': 'temp_min', 'related_value': 0.1603},
   {'related_column': 'wind_deg', 'related_value': -0.137},
   {'related_column': 'hometown_encoded', 'related_value': -0.1224},
   {'related_column': 'feels_like', 'related_value': -0.1077},
   {'related_column': 'air_pressure', 'related_value': -0.0872},
   {'related_column': 'air_humidity', 'related_value': -0.0846},
   {'related_column': 'suicide_day', 'related_value': 0.079},
   {'related_column': 'religion_encoded_buddhist', 'related_value': -0.071},
   {'related_column': 'method_encoded', 'related_value': -0.0705},
   {'related_column': 'suicide_year', 'related_value': -0.0632},
   {'related_column': 'religion_encoded_muslim', 'related_value': 0.0606},
   {'related_column': 'profession_group_encoded', 'related_value': -0.0479},
   {'related_column': 'religion_encoded_indigenous', 'related_value': -0.0457},
   {'related_column': 'religion_encoded_hindu', 'related_value': -0.0428},
   {'related_column': 'wind_speed', 'related_value': -0.0427},
   {'related_column': 'financial_condition_encoded', 'related_value': -0.0328},
   {'related_column': 'time_encoded', 'related_value': -0.0324},
   {'related_column': 'age', 'related_value': 0.0306},
   {'related_column': 'suicide_weekday_encoded', 'related_value': -0.0288},
   {'related_column': 'workplace_encoded_semi-urban', 'related_value': -0.028},
   {'related_column': 'suicide_week', 'related_value': 0.0264},
   {'related_column': 'weather_description_encoded', 'related_value': -0.0258},
   {'related_column': 'age_group_encoded', 'related_value': 0.017},
   {'related_column': 'suicide_month', 'related_value': 0.0159},
   {'related_column': 'marital_status_encoded', 'related_value': 0.0158},
   {'related_column': 'workplace_encoded_urban', 'related_value': 0.0151},
   {'related_column': 'gender_encoded_female', 'related_value': -0.0123},
   {'related_column': 'gender_encoded_male', 'related_value': 0.0112},
   {'related_column': 'gender_encoded_third gender', 'related_value': 0.0099},
   {'related_column': 'religion_encoded_christian', 'related_value': 0.0085},
   {'related_column': 'workplace_encoded_rural', 'related_value': 0.0068},
   {'related_column': 'weather_main_encoded', 'related_value': 0.0041},
   {'related_column': 'clouds_sky', 'related_value': -0.0036},
   {'related_column': 'reason_encoded', 'related_value': 0.0028}]}]

In [26]:
df_encoded.columns

Index(['age', 'latitude', 'longitude', 'feels_like', 'temp_min', 'temp_max',
       'air_pressure', 'air_humidity', 'wind_speed', 'wind_deg', 'clouds_sky',
       'time_encoded', 'suicide_day', 'suicide_month', 'suicide_year',
       'suicide_week', 'age_group_encoded', 'financial_condition_encoded',
       'weather_main_encoded', 'suicide_weekday_encoded',
       'profession_group_encoded', 'hometown_encoded', 'reason_encoded',
       'method_encoded', 'weather_description_encoded',
       'marital_status_encoded', 'gender_encoded_female',
       'gender_encoded_male', 'gender_encoded_third gender',
       'workplace_encoded_rural', 'workplace_encoded_semi-urban',
       'workplace_encoded_urban', 'religion_encoded_buddhist',
       'religion_encoded_christian', 'religion_encoded_hindu',
       'religion_encoded_indigenous', 'religion_encoded_muslim'],
      dtype='object')

In [27]:
from tqdm import tqdm
from sklearn.linear_model import BayesianRidge
from copy import deepcopy

# Start with a deep copy of the dataset so we don't affect the original
df_imputed_mice_context = deepcopy(df_encoded)
df_imputed_mice_no_context = deepcopy(df_encoded)

# === Define constraints ===
constraints = {
    'age': (0, 100),
    'latitude': (20.57, 26.63),           # Bangladesh latitude range
    'longitude': (88.0167, 92.6833),      # Bangladesh longitude range
    'feels_like': (2.6, 300.65),          # Temperature range in Kelvin (lowest and highest)
    'temp_min': (2.6, 300.65),             # Same temp range
    'temp_max': (2.6, 300.65),
    'air_pressure': (1000, 1050),          # ~1000 hPa to a bit above 1020 hPa
    'air_humidity': (70, 100),              # Percent
    'wind_speed': (3, 20),                 # ~3 to 16+ km/h, added small buffer
    'wind_deg': (0, 360),                  # Wind direction in degrees, full circle
    'clouds_sky': (0, 100),                # Cloudiness in percent
    'time_encoded': (0, 23),               # Assuming time encoded as hour in 24h format
    'suicide_day': (1, 31),                # Day of month
    'suicide_month': (1, 12),              # Month number
    'suicide_year': (2017, 2025),          # Year range you gave
    'suicide_week': (1, 52),               # Week number (approximate)
    'suicide_weekday_encoded': (0, 6),
    'age_group_encoded': (0, 6),
    'financial_condition_encoded': (0, 4),
    'weather_main_encoded': (0, 7),
}

In [28]:
def impute_column_context(column_name, context_info, df, constraints={}):
    """
    Impute missing values in column_name using only non-zero correlated columns as predictors.
    context_info should contain 'related_columns' list with dicts like:
    [{'related_column': 'col1'}, {'related_column': 'col2'}, ...]
    """
    related_cols = [r['related_column'] for r in context_info['related_columns']]
    missing_mask = df[column_name].isna()

    imputed_count = 0
    skipped_count = 0
    errors = []

    for idx in tqdm(df[missing_mask].index, desc=f"Imputing '{column_name}' (context)"):
        try:
            row = df.loc[idx]
            predictors = [col for col in related_cols if pd.notna(row[col])]

            if not predictors:  # no usable predictors for this row
                skipped_count += 1
                continue

            # Prepare training data — only rows where target & predictors are non-null
            train_df = df.dropna(subset=[column_name] + predictors)
            if train_df.empty:
                skipped_count += 1
                continue

            X_train = train_df[predictors].values
            y_train = train_df[column_name].values

            model = BayesianRidge()
            model.fit(X_train, y_train)

            # Test-time: fill missing predictors with column means
            row_input = row[predictors].copy()
            for col in predictors:
                if pd.isna(row_input[col]):
                    row_input[col] = df[col].mean()

            X_test = np.array(row_input).reshape(1, -1)
            predicted = model.predict(X_test)[0]

            # Apply constraints
            if column_name in constraints:
                lower, upper = constraints[column_name]
                if lower is not None:
                    predicted = max(predicted, lower)
                if upper is not None:
                    predicted = min(predicted, upper)

            df.at[idx, column_name] = predicted
            imputed_count += 1

        except Exception as e:
            errors.append((idx, str(e)))

    print(f"\n'{column_name}' Imputation Summary (Context):")
    print(f" - Imputed values: {imputed_count}")
    print(f" - Skipped (no predictors): {skipped_count}")
    print(f" - Errors: {len(errors)}")
    if errors:
        print("Sample Errors:")
        for idx, err in errors[:5]:
            print(f" - Row {idx}: {err}")

In [30]:
# === Run imputation for each column ===
for col_info in correlation_dict:
    impute_column_context(col_info['column_name'], col_info, df_imputed_mice_context)

Imputing 'age' (context): 100%|██████████| 206/206 [00:01<00:00, 181.22it/s]

'age' Imputation Summary (Context):
 - Imputed values: 202
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'latitude' (context): 100%|██████████| 105/105 [00:00<00:00, 182.11it/s]

'latitude' Imputation Summary (Context):
 - Imputed values: 101
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'longitude' (context): 100%|██████████| 105/105 [00:00<00:00, 200.55it/s]

'longitude' Imputation Summary (Context):
 - Imputed values: 101
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'feels_like' (context): 100%|██████████| 858/858 [00:08<00:00, 104.81it/s]

'feels_like' Imputation Summary (Context):
 - Imputed values: 854
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'temp_min' (context): 100%|██████████| 483/483 [00:02<00:00, 186.73it/s]

'temp_min' Imputation Summary (Context):
 - Imputed values: 479
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'temp_max' (context): 100%|██████████| 478/478 [00:02<00:00, 187.05it/s]

'temp_max' Imputation Summary (Context):
 - Imputed values: 474
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'air_pressure' (context): 100%|██████████| 492/492 [00:02<00:00, 189.14it/s]

'air_pressure' Imputation Summary (Context):
 - Imputed values: 488
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'air_humidity' (context): 100%|██████████| 858/858 [00:06<00:00, 124.87it/s]

'air_humidity' Imputation Summary (Context):
 - Imputed values: 854
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'wind_speed' (context): 100%|██████████| 488/488 [00:02<00:00, 186.15it/s]

'wind_speed' Imputation Summary (Context):
 - Imputed values: 484
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'wind_deg' (context): 100%|██████████| 858/858 [00:04<00:00, 194.71it/s]

'wind_deg' Imputation Summary (Context):
 - Imputed values: 854
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'clouds_sky' (context): 100%|██████████| 858/858 [00:07<00:00, 117.03it/s]

'clouds_sky' Imputation Summary (Context):
 - Imputed values: 854
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'time_encoded' (context): 100%|██████████| 195/195 [00:01<00:00, 163.17it/s]

'time_encoded' Imputation Summary (Context):
 - Imputed values: 191
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'suicide_day' (context): 100%|██████████| 39/39 [00:00<00:00, 187.12it/s]

'suicide_day' Imputation Summary (Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'suicide_month' (context): 100%|██████████| 39/39 [00:00<00:00, 198.15it/s]

'suicide_month' Imputation Summary (Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'suicide_year' (context): 100%|██████████| 39/39 [00:00<00:00, 171.02it/s]

'suicide_year' Imputation Summary (Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'suicide_week' (context): 100%|██████████| 39/39 [00:00<00:00, 197.38it/s]

'suicide_week' Imputation Summary (Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'age_group_encoded' (context): 100%|██████████| 120/120 [00:00<00:00, 195.26it/s]

'age_group_encoded' Imputation Summary (Context):
 - Imputed values: 116
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'financial_condition_encoded' (context): 100%|██████████| 736/736 [00:03<00:00, 184.69it/s]

'financial_condition_encoded' Imputation Summary (Context):
 - Imputed values: 732
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'weather_main_encoded' (context): 100%|██████████| 857/857 [00:07<00:00, 108.85it/s]

'weather_main_encoded' Imputation Summary (Context):
 - Imputed values: 853
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'suicide_weekday_encoded' (context): 100%|██████████| 39/39 [00:00<00:00, 134.33it/s]

'suicide_weekday_encoded' Imputation Summary (Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'profession_group_encoded' (context): 100%|██████████| 306/306 [00:02<00:00, 138.36it/s]

'profession_group_encoded' Imputation Summary (Context):
 - Imputed values: 302
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'hometown_encoded' (context): 100%|██████████| 27/27 [00:00<00:00, 190.47it/s]

'hometown_encoded' Imputation Summary (Context):
 - Imputed values: 23
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'reason_encoded' (context): 100%|██████████| 272/272 [00:01<00:00, 178.18it/s]

'reason_encoded' Imputation Summary (Context):
 - Imputed values: 268
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'method_encoded' (context): 100%|██████████| 47/47 [00:00<00:00, 158.23it/s]

'method_encoded' Imputation Summary (Context):
 - Imputed values: 43
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'weather_description_encoded' (context): 100%|██████████| 857/857 [00:08<00:00, 105.79it/s]

'weather_description_encoded' Imputation Summary (Context):
 - Imputed values: 853
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'marital_status_encoded' (context): 100%|██████████| 387/387 [00:02<00:00, 143.42it/s]

'marital_status_encoded' Imputation Summary (Context):
 - Imputed values: 383
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'gender_encoded_female' (context): 100%|██████████| 7/7 [00:00<00:00, 332.35it/s]

'gender_encoded_female' Imputation Summary (Context):
 - Imputed values: 3
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'gender_encoded_male' (context): 100%|██████████| 7/7 [00:00<00:00, 262.98it/s]

'gender_encoded_male' Imputation Summary (Context):
 - Imputed values: 3
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'gender_encoded_third gender' (context): 100%|██████████| 7/7 [00:00<00:00, 364.37it/s]

'gender_encoded_third gender' Imputation Summary (Context):
 - Imputed values: 3
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'workplace_encoded_rural' (context): 100%|██████████| 613/613 [00:05<00:00, 113.09it/s]

'workplace_encoded_rural' Imputation Summary (Context):
 - Imputed values: 609
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'workplace_encoded_semi-urban' (context): 100%|██████████| 613/613 [00:07<00:00, 79.08it/s]

'workplace_encoded_semi-urban' Imputation Summary (Context):
 - Imputed values: 609
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'workplace_encoded_urban' (context): 100%|██████████| 613/613 [00:04<00:00, 151.79it/s]

'workplace_encoded_urban' Imputation Summary (Context):
 - Imputed values: 609
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'religion_encoded_buddhist' (context): 100%|██████████| 39/39 [00:00<00:00, 165.12it/s]

'religion_encoded_buddhist' Imputation Summary (Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'religion_encoded_christian' (context): 100%|██████████| 39/39 [00:00<00:00, 158.56it/s]

'religion_encoded_christian' Imputation Summary (Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'religion_encoded_hindu' (context): 100%|██████████| 39/39 [00:00<00:00, 129.53it/s]

'religion_encoded_hindu' Imputation Summary (Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'religion_encoded_indigenous' (context): 100%|██████████| 39/39 [00:00<00:00, 168.07it/s]

'religion_encoded_indigenous' Imputation Summary (Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'religion_encoded_muslim' (context): 100%|██████████| 39/39 [00:00<00:00, 49.75it/s]

'religion_encoded_muslim' Imputation Summary (Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

In [31]:
missing_data_report(df_imputed_mice_context)

Group 1: Columns with >70% missing data
Empty DataFrame
Columns: [Column, Missing %, Data Type]
Index: []

Group 2: Columns with >40% to ≤70% missing data
Empty DataFrame
Columns: [Column, Missing %, Data Type]
Index: []

Group 3: Columns with >20% to ≤40% missing data
Empty DataFrame
Columns: [Column, Missing %, Data Type]
Index: []

Group 4: Columns with ≤20% missing data
                      Column  Missing % Data Type
                         age   0.247372   float64
                    latitude   0.247372   float64
                   longitude   0.247372   float64
                  feels_like   0.247372   float64
                    temp_min   0.247372   float64
                    temp_max   0.247372   float64
                air_pressure   0.247372   float64
                air_humidity   0.247372   float64
                  wind_speed   0.247372   float64
                    wind_deg   0.247372   float64
                  clouds_sky   0.247372   float64
                time_encoded   0.247372   float64
                 suicide_day   0.247372   float64
               suicide_month   0.247372   float64
                suicide_year   0.247372   float64
                suicide_week   0.247372   float64
           age_group_encoded   0.247372   float64
 financial_condition_encoded   0.247372   float64
        weather_main_encoded   0.247372   float64
     suicide_weekday_encoded   0.247372   float64
    profession_group_encoded   0.247372   float64
            hometown_encoded   0.247372   float64
              reason_encoded   0.247372   float64
              method_encoded   0.247372   float64
 weather_description_encoded   0.247372   float64
      marital_status_encoded   0.247372   float64
       gender_encoded_female   0.247372   float64
         gender_encoded_male   0.247372   float64
 gender_encoded_third gender   0.247372   float64
     workplace_encoded_rural   0.247372   float64
workplace_encoded_semi-urban   0.247372   float64
     workplace_encoded_urban   0.247372   float64
   religion_encoded_buddhist   0.247372   float64
  religion_encoded_christian   0.247372   float64
      religion_encoded_hindu   0.247372   float64
 religion_encoded_indigenous   0.247372   float64
     religion_encoded_muslim   0.247372   float64

In [32]:
def impute_column_no_context(column_name, df, constraints={}):
    """
    Impute missing values in column_name using all available non-null columns as predictors.
    """
    possible_predictors = [col for col in df.columns if col != column_name]
    missing_mask = df[column_name].isna()

    imputed_count = 0
    skipped_count = 0
    errors = []

    for idx in tqdm(df[missing_mask].index, desc=f"Imputing '{column_name}' (no context)"):
        try:
            row = df.loc[idx]
            predictors = [col for col in possible_predictors if pd.notna(row[col])]

            if not predictors:  # no usable predictors for this row
                skipped_count += 1
                continue

            # Prepare training data — only rows where target & predictors are non-null
            train_df = df.dropna(subset=[column_name] + predictors)
            if train_df.empty:
                skipped_count += 1
                continue

            X_train = train_df[predictors].values
            y_train = train_df[column_name].values

            model = BayesianRidge()
            model.fit(X_train, y_train)

            # Test-time: fill missing predictors with column means
            row_input = row[predictors].copy()
            for col in predictors:
                if pd.isna(row_input[col]):
                    row_input[col] = df[col].mean()

            X_test = np.array(row_input).reshape(1, -1)
            predicted = model.predict(X_test)[0]

            # Apply constraints
            if column_name in constraints:
                lower, upper = constraints[column_name]
                if lower is not None:
                    predicted = max(predicted, lower)
                if upper is not None:
                    predicted = min(predicted, upper)

            df.at[idx, column_name] = predicted
            imputed_count += 1

        except Exception as e:
            errors.append((idx, str(e)))

    print(f"\n'{column_name}' Imputation Summary (No Context):")
    print(f" - Imputed values: {imputed_count}")
    print(f" - Skipped (no predictors): {skipped_count}")
    print(f" - Errors: {len(errors)}")
    if errors:
        print("Sample Errors:")
        for idx, err in errors[:5]:
            print(f" - Row {idx}: {err}")

In [34]:
# Run imputation without context for each column
for col in df_imputed_mice_no_context.columns:
    impute_column_no_context(col, df_imputed_mice_no_context, constraints=constraints)

Imputing 'age' (no context): 100%|██████████| 206/206 [00:01<00:00, 115.01it/s]

'age' Imputation Summary (No Context):
 - Imputed values: 202
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'latitude' (no context): 100%|██████████| 105/105 [00:02<00:00, 41.25it/s]

'latitude' Imputation Summary (No Context):
 - Imputed values: 101
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'longitude' (no context): 100%|██████████| 105/105 [00:01<00:00, 97.10it/s]

'longitude' Imputation Summary (No Context):
 - Imputed values: 101
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'feels_like' (no context): 100%|██████████| 858/858 [00:04<00:00, 207.07it/s]

'feels_like' Imputation Summary (No Context):
 - Imputed values: 854
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'temp_min' (no context): 100%|██████████| 483/483 [00:02<00:00, 185.80it/s]

'temp_min' Imputation Summary (No Context):
 - Imputed values: 479
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'temp_max' (no context): 100%|██████████| 478/478 [00:02<00:00, 195.42it/s]

'temp_max' Imputation Summary (No Context):
 - Imputed values: 474
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'air_pressure' (no context): 100%|██████████| 492/492 [00:05<00:00, 86.20it/s]

'air_pressure' Imputation Summary (No Context):
 - Imputed values: 488
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'air_humidity' (no context): 100%|██████████| 858/858 [00:04<00:00, 181.99it/s]

'air_humidity' Imputation Summary (No Context):
 - Imputed values: 854
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'wind_speed' (no context): 100%|██████████| 488/488 [00:02<00:00, 171.53it/s]

'wind_speed' Imputation Summary (No Context):
 - Imputed values: 484
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'wind_deg' (no context): 100%|██████████| 858/858 [00:07<00:00, 110.91it/s]

'wind_deg' Imputation Summary (No Context):
 - Imputed values: 854
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'clouds_sky' (no context): 100%|██████████| 858/858 [00:04<00:00, 189.82it/s]

'clouds_sky' Imputation Summary (No Context):
 - Imputed values: 854
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'time_encoded' (no context): 100%|██████████| 195/195 [00:01<00:00, 160.72it/s]

'time_encoded' Imputation Summary (No Context):
 - Imputed values: 191
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'suicide_day' (no context): 100%|██████████| 39/39 [00:00<00:00, 135.09it/s]

'suicide_day' Imputation Summary (No Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'suicide_month' (no context): 100%|██████████| 39/39 [00:00<00:00, 156.78it/s]

'suicide_month' Imputation Summary (No Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'suicide_year' (no context): 100%|██████████| 39/39 [00:00<00:00, 180.62it/s]

'suicide_year' Imputation Summary (No Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'suicide_week' (no context): 100%|██████████| 39/39 [00:00<00:00, 195.74it/s]

'suicide_week' Imputation Summary (No Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'age_group_encoded' (no context): 100%|██████████| 120/120 [00:00<00:00, 185.47it/s]

'age_group_encoded' Imputation Summary (No Context):
 - Imputed values: 116
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'financial_condition_encoded' (no context): 100%|██████████| 736/736 [00:06<00:00, 110.57it/s]

'financial_condition_encoded' Imputation Summary (No Context):
 - Imputed values: 732
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'weather_main_encoded' (no context): 100%|██████████| 857/857 [00:04<00:00, 175.11it/s]

'weather_main_encoded' Imputation Summary (No Context):
 - Imputed values: 853
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'suicide_weekday_encoded' (no context): 100%|██████████| 39/39 [00:00<00:00, 142.34it/s]

'suicide_weekday_encoded' Imputation Summary (No Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'profession_group_encoded' (no context): 100%|██████████| 306/306 [00:01<00:00, 167.37it/s]

'profession_group_encoded' Imputation Summary (No Context):
 - Imputed values: 302
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'hometown_encoded' (no context): 100%|██████████| 27/27 [00:00<00:00, 189.83it/s]

'hometown_encoded' Imputation Summary (No Context):
 - Imputed values: 23
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'reason_encoded' (no context): 100%|██████████| 272/272 [00:01<00:00, 167.11it/s]

'reason_encoded' Imputation Summary (No Context):
 - Imputed values: 268
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'method_encoded' (no context): 100%|██████████| 47/47 [00:00<00:00, 84.36it/s]

'method_encoded' Imputation Summary (No Context):
 - Imputed values: 43
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'weather_description_encoded' (no context): 100%|██████████| 857/857 [00:07<00:00, 114.30it/s]

'weather_description_encoded' Imputation Summary (No Context):
 - Imputed values: 853
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'marital_status_encoded' (no context): 100%|██████████| 387/387 [00:02<00:00, 150.24it/s]

'marital_status_encoded' Imputation Summary (No Context):
 - Imputed values: 383
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'gender_encoded_female' (no context): 100%|██████████| 7/7 [00:00<00:00, 275.38it/s]

'gender_encoded_female' Imputation Summary (No Context):
 - Imputed values: 3
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'gender_encoded_male' (no context): 100%|██████████| 7/7 [00:00<00:00, 356.71it/s]

'gender_encoded_male' Imputation Summary (No Context):
 - Imputed values: 3
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'gender_encoded_third gender' (no context): 100%|██████████| 7/7 [00:00<00:00, 351.50it/s]

'gender_encoded_third gender' Imputation Summary (No Context):
 - Imputed values: 3
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'workplace_encoded_rural' (no context): 100%|██████████| 613/613 [00:08<00:00, 75.44it/s]

'workplace_encoded_rural' Imputation Summary (No Context):
 - Imputed values: 609
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'workplace_encoded_semi-urban' (no context): 100%|██████████| 613/613 [00:04<00:00, 142.67it/s]

'workplace_encoded_semi-urban' Imputation Summary (No Context):
 - Imputed values: 609
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'workplace_encoded_urban' (no context): 100%|██████████| 613/613 [00:03<00:00, 153.95it/s]

'workplace_encoded_urban' Imputation Summary (No Context):
 - Imputed values: 609
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'religion_encoded_buddhist' (no context): 100%|██████████| 39/39 [00:00<00:00, 164.92it/s]

'religion_encoded_buddhist' Imputation Summary (No Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'religion_encoded_christian' (no context): 100%|██████████| 39/39 [00:00<00:00, 167.25it/s]

'religion_encoded_christian' Imputation Summary (No Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'religion_encoded_hindu' (no context): 100%|██████████| 39/39 [00:00<00:00, 155.01it/s]

'religion_encoded_hindu' Imputation Summary (No Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'religion_encoded_indigenous' (no context): 100%|██████████| 39/39 [00:00<00:00, 134.54it/s]

'religion_encoded_indigenous' Imputation Summary (No Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

Imputing 'religion_encoded_muslim' (no context): 100%|██████████| 39/39 [00:00<00:00, 87.64it/s]

'religion_encoded_muslim' Imputation Summary (No Context):
 - Imputed values: 35
 - Skipped (no predictors): 4
 - Errors: 0

In [35]:
missing_data_report(df_imputed_mice_no_context)

Group 1: Columns with >70% missing data
Empty DataFrame
Columns: [Column, Missing %, Data Type]
Index: []

Group 2: Columns with >40% to ≤70% missing data
Empty DataFrame
Columns: [Column, Missing %, Data Type]
Index: []

Group 3: Columns with >20% to ≤40% missing data
Empty DataFrame
Columns: [Column, Missing %, Data Type]
Index: []

Group 4: Columns with ≤20% missing data
                      Column  Missing % Data Type
                         age   0.247372   float64
                    latitude   0.247372   float64
                   longitude   0.247372   float64
                  feels_like   0.247372   float64
                    temp_min   0.247372   float64
                    temp_max   0.247372   float64
                air_pressure   0.247372   float64
                air_humidity   0.247372   float64
                  wind_speed   0.247372   float64
                    wind_deg   0.247372   float64
                  clouds_sky   0.247372   float64
                time_encoded   0.247372   float64
                 suicide_day   0.247372   float64
               suicide_month   0.247372   float64
                suicide_year   0.247372   float64
                suicide_week   0.247372   float64
           age_group_encoded   0.247372   float64
 financial_condition_encoded   0.247372   float64
        weather_main_encoded   0.247372   float64
     suicide_weekday_encoded   0.247372   float64
    profession_group_encoded   0.247372   float64
            hometown_encoded   0.247372   float64
              reason_encoded   0.247372   float64
              method_encoded   0.247372   float64
 weather_description_encoded   0.247372   float64
      marital_status_encoded   0.247372   float64
       gender_encoded_female   0.247372   float64
         gender_encoded_male   0.247372   float64
 gender_encoded_third gender   0.247372   float64
     workplace_encoded_rural   0.247372   float64
workplace_encoded_semi-urban   0.247372   float64
     workplace_encoded_urban   0.247372   float64
   religion_encoded_buddhist   0.247372   float64
  religion_encoded_christian   0.247372   float64
      religion_encoded_hindu   0.247372   float64
 religion_encoded_indigenous   0.247372   float64
     religion_encoded_muslim   0.247372   float64

## After imputation processing

In [36]:
import numpy as np

# Define one-hot groups
one_hot_groups = {
    'gender': [
        'gender_encoded_female',
        'gender_encoded_male',
        'gender_encoded_third gender'
    ],
    'workplace': [
        'workplace_encoded_rural',
        'workplace_encoded_semi-urban',
        'workplace_encoded_urban'
    ],
    'religion': [
        'religion_encoded_buddhist',
        'religion_encoded_christian',
        'religion_encoded_hindu',
        'religion_encoded_indigenous',
        'religion_encoded_muslim'
    ]
}

# Function to fix one-hot encoding
def fix_one_hot_group(df, columns):
    data = df[columns].to_numpy()
    max_indices = np.argmax(data, axis=1)  # index of max value in each row

    # Set the max column to 1, others to 0
    fixed_data = np.zeros_like(data)
    fixed_data[np.arange(data.shape[0]), max_indices] = 1

    df[columns] = fixed_data
    return df

### fixing one hot columns for context data

In [37]:
# Apply fix to each group
for group_cols in one_hot_groups.values():
    df_imputed_mice_context = fix_one_hot_group(df_imputed_mice_context, group_cols)

### fixing one hot columns for no context data

In [38]:
# Apply fix to each group
for group_cols in one_hot_groups.values():
    df_imputed_mice_no_context = fix_one_hot_group(df_imputed_mice_no_context, group_cols)

In [39]:
# Define your constraints
ordinal_constraints = {
    'suicide_weekday_encoded': (0, 6),
    'age_group_encoded': (0, 6),
    'financial_condition_encoded': (0, 4),
    'weather_main_encoded': (0, 7),
}

## fixing ordinal columns for context data

In [40]:
# Apply rounding and clip to valid range
for col, (low, high) in ordinal_constraints.items():
    if col in df_imputed_mice_context.columns:
        df_imputed_mice_context[col] = df_imputed_mice_context[col].round().clip(lower=low, upper=high)

## fixing ordinal columns for no context data

In [41]:
# Apply rounding and clip to valid range
for col, (low, high) in ordinal_constraints.items():
    if col in df_imputed_mice_context.columns:
        df_imputed_mice_no_context[col] = df_imputed_mice_no_context[col].round().clip(lower=low, upper=high)

In [42]:
df_imputed_mice_context.tail(5)

,age,latitude,longitude,feels_like,temp_min,temp_max,air_pressure,air_humidity,wind_speed,wind_deg,...,gender_encoded_male,gender_encoded_third gender,workplace_encoded_rural,workplace_encoded_semi-urban,workplace_encoded_urban,religion_encoded_buddhist,religion_encoded_christian,religion_encoded_hindu,religion_encoded_indigenous,religion_encoded_muslim
1612,15.000000,23.707123,90.067937,-16.939983,55.508111,65.034355,1010.215950,408.127411,6.177175,-577.892755,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1613,27.000000,23.740193,90.302765,143.521566,178.146784,180.409645,1002.507166,253.150332,3.510377,-226.057716,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1614,9.000000,23.825789,90.068352,203.686195,224.055094,226.010537,1004.803463,187.071699,4.021778,-86.706507,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1615,22.368872,23.898795,89.129554,-74.633303,12.500000,23.700000,1019.000000,457.222918,8.000000,-771.356660,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1616,26.000000,22.655478,89.794181,-49.798064,29.800000,36.600000,1003.800000,458.643328,3.800000,-656.035418,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [43]:
df_imputed_mice_no_context.tail(5)

,age,latitude,longitude,feels_like,temp_min,temp_max,air_pressure,air_humidity,wind_speed,wind_deg,...,gender_encoded_male,gender_encoded_third gender,workplace_encoded_rural,workplace_encoded_semi-urban,workplace_encoded_urban,religion_encoded_buddhist,religion_encoded_christian,religion_encoded_hindu,religion_encoded_indigenous,religion_encoded_muslim
1612,15.000000,23.707123,90.067937,119.627275,121.154277,129.013497,1009.870911,93.222221,5.302351,62.488973,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1613,27.000000,23.740193,90.302765,128.211925,138.185201,141.419927,1002.570011,93.227106,4.001096,61.653333,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1614,9.000000,23.825789,90.068352,166.734308,171.723086,174.944481,1004.899221,91.553503,4.760535,80.759772,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1615,22.368872,23.898795,89.129554,3.628097,12.500000,23.700000,1019.000000,99.502018,8.000000,0.000000,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1616,26.000000,22.655478,89.794181,15.713082,29.800000,36.600000,1003.800000,98.716658,3.800000,14.131072,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [46]:
# # prompt: give me the code make the latest df downloadable and download that db named final_suicide_cleaned.xlsx ins excel format

# # Make the latest DataFrame downloadable
# from google.colab import files

# # Specify the filename for the Excel file
# filename1 = '6_mice_context.xlsx'

# # Save the DataFrame to an Excel file
# df_imputed_mice_context.to_excel(filename1, index=False)

# # Download the file
# files.download(filename1)

In [47]:
# # prompt: give me the code make the latest df downloadable and download that db named final_suicide_cleaned.xlsx ins excel format

# # Make the latest DataFrame downloadable
# from google.colab import files

# # Specify the filename for the Excel file
# filename2 = '7_mice_no_context.xlsx'

# # Save the DataFrame to an Excel file
# df_imputed_mice_no_context.to_excel(filename2, index=False)

# # Download the file
# files.download(filename2)