# beginning

In [53]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [54]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# data loading

In [55]:
df_encoded = pd.read_excel("/content/drive/MyDrive/capstone/datasets/5_encoded.xlsx")

In [56]:
df_encoded.head()

,age,latitude,longitude,feels_like,temp_min,temp_max,air_pressure,air_humidity,wind_speed,wind_deg,...,gender_encoded_male,gender_encoded_third gender,workplace_encoded_rural,workplace_encoded_semi-urban,workplace_encoded_urban,religion_encoded_buddhist,religion_encoded_christian,religion_encoded_hindu,religion_encoded_indigenous,religion_encoded_muslim
0,NaN,23.960600,91.119089,302.86,299.15,299.15,1008.0,83.0,2.10,320.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,20.0,24.899220,91.868527,299.17,295.57,295.57,1012.0,96.0,1.39,116.0,...,1.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0
2,14.0,23.832984,89.966688,304.33,301.15,301.15,1004.0,78.0,3.60,190.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,NaN,24.850066,89.372843,303.67,299.34,299.34,1003.0,91.0,2.64,186.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,18.0,23.764386,90.389014,304.49,300.15,300.15,1004.0,83.0,1.99,154.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [57]:
df_encoded.shape

(1617, 37)

In [58]:
def missing_data_report(df):
    # Calculate the percentage of missing data for each column
    missing_percentage = df.isna().mean() * 100

    # Get the data types of each column
    data_types = df.dtypes

    # Create a DataFrame for the missing data summary including data types
    missing_data_summary = pd.DataFrame({
        'Column': missing_percentage.index,
        'Missing Percentage': missing_percentage.values,
        'Data Type': data_types.values
    })

    # Define the four groups based on missing percentage
    group_1 = missing_data_summary[missing_data_summary['Missing Percentage'] > 70][['Column', 'Missing Percentage', 'Data Type']]
    group_2 = missing_data_summary[(missing_data_summary['Missing Percentage'] > 40) & (missing_data_summary['Missing Percentage'] <= 70)][['Column', 'Missing Percentage', 'Data Type']]
    group_3 = missing_data_summary[(missing_data_summary['Missing Percentage'] > 20) & (missing_data_summary['Missing Percentage'] <= 40)][['Column', 'Missing Percentage', 'Data Type']]
    group_4 = missing_data_summary[missing_data_summary['Missing Percentage'] <= 20][['Column', 'Missing Percentage', 'Data Type']]

    # Sort each group by missing percentage in descending order (most missing to least missing)
    group_1 = group_1.sort_values(by='Missing Percentage', ascending=False).reset_index(drop=True)
    group_2 = group_2.sort_values(by='Missing Percentage', ascending=False).reset_index(drop=True)
    group_3 = group_3.sort_values(by='Missing Percentage', ascending=False).reset_index(drop=True)
    group_4 = group_4.sort_values(by='Missing Percentage', ascending=False).reset_index(drop=True)


    # Rename columns for clarity
    group_1.columns = ['Column', 'Missing %', 'Data Type']
    group_2.columns = ['Column', 'Missing %', 'Data Type']
    group_3.columns = ['Column', 'Missing %', 'Data Type']
    group_4.columns = ['Column', 'Missing %', 'Data Type']

    # Display each group one by one, from most missing to least missing
    print("Group 1: Columns with >70% missing data")
    print(group_1.to_string(index=False))
    print("\nGroup 2: Columns with >40% to ≤70% missing data")
    print(group_2.to_string(index=False))
    print("\nGroup 3: Columns with >20% to ≤40% missing data")
    print(group_3.to_string(index=False))
    print("\nGroup 4: Columns with ≤20% missing data")
    print(group_4.to_string(index=False))

In [59]:
missing_data_report(df_encoded)

Group 1: Columns with >70% missing data
Empty DataFrame
Columns: [Column, Missing %, Data Type]
Index: []

Group 2: Columns with >40% to ≤70% missing data
                     Column  Missing % Data Type
                 feels_like  53.061224   float64
               air_humidity  53.061224   float64
                   wind_deg  53.061224   float64
                 clouds_sky  53.061224   float64
       weather_main_encoded  52.999382   float64
weather_description_encoded  52.999382   float64
financial_condition_encoded  45.516388   float64

Group 3: Columns with >20% to ≤40% missing data
                      Column  Missing % Data Type
workplace_encoded_semi-urban  37.909709   float64
     workplace_encoded_urban  37.909709   float64
     workplace_encoded_rural  37.909709   float64
                air_pressure  30.426716   float64
                  wind_speed  30.179344   float64
                    temp_min  29.870130   float64
                    temp_max  29.560915   float64
      marital_status_encoded  23.933210   float64

Group 4: Columns with ≤20% missing data
                     Column  Missing % Data Type
   profession_group_encoded  18.923933   float64
             reason_encoded  16.821274   float64
                        age  12.739641   float64
               time_encoded  12.059369   float64
          age_group_encoded   7.421150   float64
                   latitude   6.493506   float64
                  longitude   6.493506   float64
             method_encoded   2.906617   float64
              suicide_month   2.411874   float64
                suicide_day   2.411874   float64
    suicide_weekday_encoded   2.411874   float64
               suicide_week   2.411874   float64
               suicide_year   2.411874   float64
  religion_encoded_buddhist   2.411874   float64
    religion_encoded_muslim   2.411874   float64
religion_encoded_indigenous   2.411874   float64
     religion_encoded_hindu   2.411874   float64
 religion_encoded_christian   2.411874   float64
           hometown_encoded   1.669759   float64
gender_encoded_third gender   0.432900   float64
      gender_encoded_female   0.432900   float64
        gender_encoded_male   0.432900   float64

In [60]:
df_encoded.columns

Index(['age', 'latitude', 'longitude', 'feels_like', 'temp_min', 'temp_max',
       'air_pressure', 'air_humidity', 'wind_speed', 'wind_deg', 'clouds_sky',
       'time_encoded', 'suicide_day', 'suicide_month', 'suicide_year',
       'suicide_week', 'age_group_encoded', 'financial_condition_encoded',
       'weather_main_encoded', 'suicide_weekday_encoded',
       'profession_group_encoded', 'hometown_encoded', 'reason_encoded',
       'method_encoded', 'weather_description_encoded',
       'marital_status_encoded', 'gender_encoded_female',
       'gender_encoded_male', 'gender_encoded_third gender',
       'workplace_encoded_rural', 'workplace_encoded_semi-urban',
       'workplace_encoded_urban', 'religion_encoded_buddhist',
       'religion_encoded_christian', 'religion_encoded_hindu',
       'religion_encoded_indigenous', 'religion_encoded_muslim'],
      dtype='object')

In [61]:
import pandas as pd

def compute_sorted_correlations(df, threshold=0.0):
    corr_matrix = df.corr()

    result = []

    for col in corr_matrix.columns:
        # Drop self-correlation
        related = corr_matrix[col].drop(labels=[col])

        # Keep only correlations above threshold (excluding exact 0)
        related_filtered = related[related.abs() > threshold]

        # Sort by absolute correlation descending
        related_sorted = related_filtered.reindex(related_filtered.abs().sort_values(ascending=False).index)

        # Format results
        related_list = [
            {'related_column': other_col, 'related_value': round(related_value, 4)}
            for other_col, related_value in related_sorted.items()
        ]

        result.append({
            'column_name': col,
            'related_columns': related_list
        })

    return result

In [62]:
correlation_dict = compute_sorted_correlations(df_encoded)

from pprint import pprint
display(correlation_dict[:2])  # preview first 2 entries

[{'column_name': 'age',
  'related_columns': [{'related_column': 'age_group_encoded',
    'related_value': 0.8346},
   {'related_column': 'profession_group_encoded', 'related_value': -0.6141},
   {'related_column': 'gender_encoded_male', 'related_value': 0.2746},
   {'related_column': 'gender_encoded_female', 'related_value': -0.2718},
   {'related_column': 'marital_status_encoded', 'related_value': 0.1761},
   {'related_column': 'method_encoded', 'related_value': -0.1149},
   {'related_column': 'reason_encoded', 'related_value': -0.0955},
   {'related_column': 'temp_max', 'related_value': 0.0686},
   {'related_column': 'temp_min', 'related_value': 0.0662},
   {'related_column': 'workplace_encoded_rural', 'related_value': -0.0633},
   {'related_column': 'feels_like', 'related_value': 0.0549},
   {'related_column': 'clouds_sky', 'related_value': -0.0535},
   {'related_column': 'suicide_day', 'related_value': -0.0454},
   {'related_column': 'religion_encoded_muslim', 'related_value': -0.0452},
   {'related_column': 'workplace_encoded_urban', 'related_value': 0.0448},
   {'related_column': 'air_pressure', 'related_value': -0.0442},
   {'related_column': 'longitude', 'related_value': -0.0363},
   {'related_column': 'suicide_weekday_encoded', 'related_value': -0.036},
   {'related_column': 'religion_encoded_christian', 'related_value': 0.0357},
   {'related_column': 'suicide_year', 'related_value': -0.0346},
   {'related_column': 'time_encoded', 'related_value': -0.0335},
   {'related_column': 'religion_encoded_hindu', 'related_value': 0.0321},
   {'related_column': 'workplace_encoded_semi-urban', 'related_value': 0.0313},
   {'related_column': 'latitude', 'related_value': 0.0306},
   {'related_column': 'gender_encoded_third gender', 'related_value': -0.0259},
   {'related_column': 'weather_main_encoded', 'related_value': -0.0257},
   {'related_column': 'financial_condition_encoded', 'related_value': 0.0228},
   {'related_column': 'religion_encoded_indigenous', 'related_value': 0.0208},
   {'related_column': 'suicide_week', 'related_value': 0.0208},
   {'related_column': 'religion_encoded_buddhist', 'related_value': 0.0205},
   {'related_column': 'wind_speed', 'related_value': -0.0198},
   {'related_column': 'air_humidity', 'related_value': -0.0181},
   {'related_column': 'hometown_encoded', 'related_value': 0.0174},
   {'related_column': 'weather_description_encoded', 'related_value': 0.0155},
   {'related_column': 'suicide_month', 'related_value': 0.0131},
   {'related_column': 'wind_deg', 'related_value': -0.01}]},
 {'column_name': 'latitude',
  'related_columns': [{'related_column': 'longitude',
    'related_value': -0.4123},
   {'related_column': 'temp_max', 'related_value': 0.1622},
   {'related_column': 'temp_min', 'related_value': 0.1603},
   {'related_column': 'wind_deg', 'related_value': -0.137},
   {'related_column': 'hometown_encoded', 'related_value': -0.1224},
   {'related_column': 'feels_like', 'related_value': -0.1077},
   {'related_column': 'air_pressure', 'related_value': -0.0872},
   {'related_column': 'air_humidity', 'related_value': -0.0846},
   {'related_column': 'suicide_day', 'related_value': 0.079},
   {'related_column': 'religion_encoded_buddhist', 'related_value': -0.071},
   {'related_column': 'method_encoded', 'related_value': -0.0705},
   {'related_column': 'suicide_year', 'related_value': -0.0632},
   {'related_column': 'religion_encoded_muslim', 'related_value': 0.0606},
   {'related_column': 'profession_group_encoded', 'related_value': -0.0479},
   {'related_column': 'religion_encoded_indigenous', 'related_value': -0.0457},
   {'related_column': 'religion_encoded_hindu', 'related_value': -0.0428},
   {'related_column': 'wind_speed', 'related_value': -0.0427},
   {'related_column': 'financial_condition_encoded', 'related_value': -0.0328},
   {'related_column': 'time_encoded', 'related_value': -0.0324},
   {'related_column': 'age', 'related_value': 0.0306},
   {'related_column': 'suicide_weekday_encoded', 'related_value': -0.0288},
   {'related_column': 'workplace_encoded_semi-urban', 'related_value': -0.028},
   {'related_column': 'suicide_week', 'related_value': 0.0264},
   {'related_column': 'weather_description_encoded', 'related_value': -0.0258},
   {'related_column': 'age_group_encoded', 'related_value': 0.017},
   {'related_column': 'suicide_month', 'related_value': 0.0159},
   {'related_column': 'marital_status_encoded', 'related_value': 0.0158},
   {'related_column': 'workplace_encoded_urban', 'related_value': 0.0151},
   {'related_column': 'gender_encoded_female', 'related_value': -0.0123},
   {'related_column': 'gender_encoded_male', 'related_value': 0.0112},
   {'related_column': 'gender_encoded_third gender', 'related_value': 0.0099},
   {'related_column': 'religion_encoded_christian', 'related_value': 0.0085},
   {'related_column': 'workplace_encoded_rural', 'related_value': 0.0068},
   {'related_column': 'weather_main_encoded', 'related_value': 0.0041},
   {'related_column': 'clouds_sky', 'related_value': -0.0036},
   {'related_column': 'reason_encoded', 'related_value': 0.0028}]}]

In [63]:
df_encoded.columns

Index(['age', 'latitude', 'longitude', 'feels_like', 'temp_min', 'temp_max',
       'air_pressure', 'air_humidity', 'wind_speed', 'wind_deg', 'clouds_sky',
       'time_encoded', 'suicide_day', 'suicide_month', 'suicide_year',
       'suicide_week', 'age_group_encoded', 'financial_condition_encoded',
       'weather_main_encoded', 'suicide_weekday_encoded',
       'profession_group_encoded', 'hometown_encoded', 'reason_encoded',
       'method_encoded', 'weather_description_encoded',
       'marital_status_encoded', 'gender_encoded_female',
       'gender_encoded_male', 'gender_encoded_third gender',
       'workplace_encoded_rural', 'workplace_encoded_semi-urban',
       'workplace_encoded_urban', 'religion_encoded_buddhist',
       'religion_encoded_christian', 'religion_encoded_hindu',
       'religion_encoded_indigenous', 'religion_encoded_muslim'],
      dtype='object')

In [64]:
from tqdm import tqdm
from sklearn.impute import KNNImputer
from copy import deepcopy

# Start with a deep copy of the dataset so we don't affect the original
df_imputed_knn_context = deepcopy(df_encoded)
df_imputed_knn_no_context = deepcopy(df_encoded)

# === Define constraints ===
constraints = {
    'age': (0, 100),
    'latitude': (20.57, 26.63),           # Bangladesh latitude range
    'longitude': (88.0167, 92.6833),      # Bangladesh longitude range
    'feels_like': (2.6, 300.65),          # Temperature range in Kelvin (lowest and highest)
    'temp_min': (2.6, 300.65),             # Same temp range
    'temp_max': (2.6, 300.65),
    'air_pressure': (1000, 1050),          # ~1000 hPa to a bit above 1020 hPa
    'air_humidity': (70, 100),              # Percent
    'wind_speed': (3, 20),                 # ~3 to 16+ km/h, added small buffer
    'wind_deg': (0, 360),                  # Wind direction in degrees, full circle
    'clouds_sky': (0, 100),                # Cloudiness in percent
    'time_encoded': (0, 23),               # Assuming time encoded as hour in 24h format
    'suicide_day': (1, 31),                # Day of month
    'suicide_month': (1, 12),              # Month number
    'suicide_year': (2017, 2025),          # Year range you gave
    'suicide_week': (1, 52),               # Week number (approximate)
    'suicide_weekday_encoded': (0, 6),
    'age_group_encoded': (0, 6),
    'financial_condition_encoded': (0, 4),
    'weather_main_encoded': (0, 7),
}

In [65]:
def impute_with_knn_context(df, context_info, constraints={}, n_neighbors=5):
    for entry in tqdm(context_info, desc="KNN Context Imputation"):
        column_name = entry['column_name']
        predictors = [r['related_column'] for r in entry['related_columns'] if r['related_column'] in df.columns]

        missing_mask = df[column_name].isna()
        imputed_count = 0
        skipped_count = 0
        errors = []

        if not predictors or missing_mask.sum() == 0:
            continue

        df_subset = df[predictors + [column_name]]

        try:
            imputer = KNNImputer(n_neighbors=n_neighbors)
            imputed_array = imputer.fit_transform(df_subset)
            imputed_df = pd.DataFrame(imputed_array, columns=df_subset.columns, index=df_subset.index)

            mask = df[column_name].isna()
            df.loc[mask, column_name] = imputed_df.loc[mask, column_name]
            imputed_count = mask.sum() - df[column_name].isna().sum()

            if column_name in constraints:
                lower, upper = constraints[column_name]
                df[column_name] = df[column_name].clip(lower=lower, upper=upper)

        except Exception as e:
            errors.append(str(e))

        print(f"\n'{column_name}' Imputation Summary (Context):")
        print(f" - Imputed values: {imputed_count}")
        print(f" - Skipped (no predictors): {skipped_count}")
        print(f" - Errors: {len(errors)}")
        if errors:
            for err in errors[:5]:
                print(f" - Error: {err}")

    return df

In [66]:
# def impute_with_knn_context(df, context_list, constraints=None, n_neighbors=5):
#     for entry in tqdm(context_list, desc="KNN Context Imputation"):
#         column_name = entry['column_name']
#         related_columns = [rel['related_column'] for rel in entry['related_columns']]

#         if column_name not in df.columns or df[column_name].isnull().sum() == 0:
#             continue  # Skip if no missing values to impute

#         context_cols = [col for col in related_columns if col in df.columns]
#         if not context_cols:
#             print(f"Skipping '{column_name}': no valid context columns found.")
#             continue

#         columns_for_imputation = context_cols + [column_name]
#         df_subset = df[columns_for_imputation]

#         try:
#             # Fit KNNImputer on full subset (including missing in context columns)
#             imputer = KNNImputer(n_neighbors=n_neighbors)
#             imputed_array = imputer.fit_transform(df_subset)

#             # Extract the imputed target column (last column)
#             imputed_target = imputed_array[:, -1]
#             imputed_series = pd.Series(imputed_target, index=df_subset.index)

#             # Only update missing values in original dataframe at matching indices
#             mask = df[column_name].isnull()
#             df.loc[mask, column_name] = imputed_series[mask]

#             # Apply constraints if provided
#             if constraints and column_name in constraints:
#                 min_val, max_val = constraints[column_name]
#                 df[column_name] = df[column_name].clip(lower=min_val, upper=max_val)

#             print(f"✅ Imputed '{column_name}' using context columns: {context_cols}")
#             print(f"   🔸 Remaining missing: {df[column_name].isnull().sum()}")

#         except Exception as e:
#             print(f"❌ Error imputing '{column_name}': {e}")

#     return df

In [67]:
df_imputed_knn_context = impute_with_knn_context(df_imputed_knn_context, correlation_dict, constraints, n_neighbors=5)

KNN Context Imputation:   3%|▎         | 1/37 [00:00<00:15,  2.35it/s]

'age' Imputation Summary (Context):
 - Imputed values: 206
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:   5%|▌         | 2/37 [00:00<00:14,  2.49it/s]

'latitude' Imputation Summary (Context):
 - Imputed values: 105
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:   8%|▊         | 3/37 [00:01<00:13,  2.61it/s]

'longitude' Imputation Summary (Context):
 - Imputed values: 105
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  11%|█         | 4/37 [00:01<00:12,  2.67it/s]

'feels_like' Imputation Summary (Context):
 - Imputed values: 858
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  14%|█▎        | 5/37 [00:01<00:11,  2.70it/s]

'temp_min' Imputation Summary (Context):
 - Imputed values: 483
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  16%|█▌        | 6/37 [00:02<00:11,  2.74it/s]

'temp_max' Imputation Summary (Context):
 - Imputed values: 478
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  19%|█▉        | 7/37 [00:02<00:10,  2.81it/s]

'air_pressure' Imputation Summary (Context):
 - Imputed values: 492
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  22%|██▏       | 8/37 [00:02<00:10,  2.74it/s]

'air_humidity' Imputation Summary (Context):
 - Imputed values: 858
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  24%|██▍       | 9/37 [00:03<00:11,  2.51it/s]

'wind_speed' Imputation Summary (Context):
 - Imputed values: 488
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  27%|██▋       | 10/37 [00:03<00:11,  2.29it/s]

'wind_deg' Imputation Summary (Context):
 - Imputed values: 858
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  30%|██▉       | 11/37 [00:04<00:11,  2.24it/s]

'clouds_sky' Imputation Summary (Context):
 - Imputed values: 858
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  32%|███▏      | 12/37 [00:04<00:11,  2.18it/s]

'time_encoded' Imputation Summary (Context):
 - Imputed values: 195
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  35%|███▌      | 13/37 [00:05<00:11,  2.17it/s]

'suicide_day' Imputation Summary (Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  38%|███▊      | 14/37 [00:05<00:10,  2.15it/s]

'suicide_month' Imputation Summary (Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  41%|████      | 15/37 [00:06<00:10,  2.19it/s]

'suicide_year' Imputation Summary (Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  43%|████▎     | 16/37 [00:06<00:09,  2.24it/s]

'suicide_week' Imputation Summary (Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  46%|████▌     | 17/37 [00:07<00:08,  2.47it/s]

'age_group_encoded' Imputation Summary (Context):
 - Imputed values: 120
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  49%|████▊     | 18/37 [00:07<00:07,  2.69it/s]

'financial_condition_encoded' Imputation Summary (Context):
 - Imputed values: 736
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  51%|█████▏    | 19/37 [00:07<00:06,  2.94it/s]

'weather_main_encoded' Imputation Summary (Context):
 - Imputed values: 857
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  54%|█████▍    | 20/37 [00:07<00:05,  3.16it/s]

'suicide_weekday_encoded' Imputation Summary (Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  57%|█████▋    | 21/37 [00:08<00:04,  3.27it/s]

'profession_group_encoded' Imputation Summary (Context):
 - Imputed values: 306
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  59%|█████▉    | 22/37 [00:08<00:04,  3.44it/s]

'hometown_encoded' Imputation Summary (Context):
 - Imputed values: 27
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  62%|██████▏   | 23/37 [00:08<00:03,  3.58it/s]

'reason_encoded' Imputation Summary (Context):
 - Imputed values: 272
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  65%|██████▍   | 24/37 [00:08<00:03,  3.69it/s]

'method_encoded' Imputation Summary (Context):
 - Imputed values: 47
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  70%|███████   | 26/37 [00:09<00:02,  4.30it/s]

'weather_description_encoded' Imputation Summary (Context):
 - Imputed values: 857
 - Skipped (no predictors): 0
 - Errors: 0

'marital_status_encoded' Imputation Summary (Context):
 - Imputed values: 387
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  76%|███████▌  | 28/37 [00:09<00:01,  5.43it/s]

'gender_encoded_female' Imputation Summary (Context):
 - Imputed values: 7
 - Skipped (no predictors): 0
 - Errors: 0

'gender_encoded_male' Imputation Summary (Context):
 - Imputed values: 7
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  81%|████████  | 30/37 [00:09<00:01,  6.16it/s]

'gender_encoded_third gender' Imputation Summary (Context):
 - Imputed values: 7
 - Skipped (no predictors): 0
 - Errors: 0

'workplace_encoded_rural' Imputation Summary (Context):
 - Imputed values: 613
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation:  86%|████████▋ | 32/37 [00:10<00:00,  7.04it/s]

'workplace_encoded_semi-urban' Imputation Summary (Context):
 - Imputed values: 613
 - Skipped (no predictors): 0
 - Errors: 0

'workplace_encoded_urban' Imputation Summary (Context):
 - Imputed values: 613
 - Skipped (no predictors): 0
 - Errors: 0

'religion_encoded_buddhist' Imputation Summary (Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

'religion_encoded_christian' Imputation Summary (Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

'religion_encoded_hindu' Imputation Summary (Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

KNN Context Imputation: 100%|██████████| 37/37 [00:10<00:00,  3.62it/s]

'religion_encoded_indigenous' Imputation Summary (Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

'religion_encoded_muslim' Imputation Summary (Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

In [68]:
missing_data_report(df_imputed_knn_context)

Group 1: Columns with >70% missing data
Empty DataFrame
Columns: [Column, Missing %, Data Type]
Index: []

Group 2: Columns with >40% to ≤70% missing data
Empty DataFrame
Columns: [Column, Missing %, Data Type]
Index: []

Group 3: Columns with >20% to ≤40% missing data
Empty DataFrame
Columns: [Column, Missing %, Data Type]
Index: []

Group 4: Columns with ≤20% missing data
                      Column  Missing % Data Type
                         age        0.0   float64
                    latitude        0.0   float64
                   longitude        0.0   float64
                  feels_like        0.0   float64
                    temp_min        0.0   float64
                    temp_max        0.0   float64
                air_pressure        0.0   float64
                air_humidity        0.0   float64
                  wind_speed        0.0   float64
                    wind_deg        0.0   float64
                  clouds_sky        0.0   float64
                time_encoded        0.0   float64
                 suicide_day        0.0   float64
               suicide_month        0.0   float64
                suicide_year        0.0   float64
                suicide_week        0.0   float64
           age_group_encoded        0.0   float64
 financial_condition_encoded        0.0   float64
        weather_main_encoded        0.0   float64
     suicide_weekday_encoded        0.0   float64
    profession_group_encoded        0.0   float64
            hometown_encoded        0.0   float64
              reason_encoded        0.0   float64
              method_encoded        0.0   float64
 weather_description_encoded        0.0   float64
      marital_status_encoded        0.0   float64
       gender_encoded_female        0.0   float64
         gender_encoded_male        0.0   float64
 gender_encoded_third gender        0.0   float64
     workplace_encoded_rural        0.0   float64
workplace_encoded_semi-urban        0.0   float64
     workplace_encoded_urban        0.0   float64
   religion_encoded_buddhist        0.0   float64
  religion_encoded_christian        0.0   float64
      religion_encoded_hindu        0.0   float64
 religion_encoded_indigenous        0.0   float64
     religion_encoded_muslim        0.0   float64

In [69]:
def impute_with_knn_no_context(df, constraints={}, n_neighbors=5):
    """
    KNN imputation using all other columns as predictors.
    Optimized: fits KNN once per target column and returns the modified df.
    """
    for column_name in tqdm(df.columns, desc="KNN No-Context Imputation"):
        missing_mask = df[column_name].isna()
        imputed_count = 0
        skipped_count = 0
        errors = []

        if missing_mask.sum() == 0:
            continue

        # Use all other columns as predictors
        predictors = [col for col in df.columns if col != column_name]
        if not predictors:
            skipped_count += 1
            continue

        # Subset dataframe for KNN
        df_subset = df[predictors + [column_name]]

        try:
            imputer = KNNImputer(n_neighbors=n_neighbors)
            imputed_array = imputer.fit_transform(df_subset)
            imputed_df = pd.DataFrame(imputed_array, columns=df_subset.columns, index=df_subset.index)

            # Update only missing values
            mask = df[column_name].isna()
            df.loc[mask, column_name] = imputed_df.loc[mask, column_name]
            imputed_count = mask.sum() - df[column_name].isna().sum()

            # Apply constraints
            if column_name in constraints:
                lower, upper = constraints[column_name]
                df[column_name] = df[column_name].clip(lower=lower, upper=upper)

        except Exception as e:
            errors.append(str(e))

        print(f"\n'{column_name}' Imputation Summary (No Context):")
        print(f" - Imputed values: {imputed_count}")
        print(f" - Skipped (no predictors): {skipped_count}")
        print(f" - Errors: {len(errors)}")
        if errors:
            for err in errors[:5]:
                print(f" - Error: {err}")

    return df

In [70]:
# def impute_with_knn_no_context(df, constraints=None, n_neighbors=5):
#     # Copy to avoid modifying original
#     df_result = df.copy()

#     try:
#         imputer = KNNImputer(n_neighbors=n_neighbors)
#         imputed_array = imputer.fit_transform(df_result)

#         # Put back imputed values
#         df_imputed = pd.DataFrame(imputed_array, columns=df_result.columns, index=df_result.index)

#         # Apply constraints if provided
#         if constraints:
#             for col, (min_val, max_val) in constraints.items():
#                 if col in df_imputed.columns:
#                     df_imputed[col] = df_imputed[col].clip(lower=min_val, upper=max_val)

#         print("✅ Imputation without context done.")
#         return df_imputed

#     except Exception as e:
#         print(f"❌ Error during KNN imputation without context: {e}")
#         return df_result  # return original in case of failure

In [71]:
df_imputed_knn_no_context = impute_with_knn_no_context(df_imputed_knn_no_context, constraints=constraints, n_neighbors=5)

KNN No-Context Imputation:   3%|▎         | 1/37 [00:00<00:14,  2.47it/s]

'age' Imputation Summary (No Context):
 - Imputed values: 206
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:   5%|▌         | 2/37 [00:00<00:13,  2.61it/s]

'latitude' Imputation Summary (No Context):
 - Imputed values: 105
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:   8%|▊         | 3/37 [00:01<00:12,  2.63it/s]

'longitude' Imputation Summary (No Context):
 - Imputed values: 105
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  11%|█         | 4/37 [00:01<00:12,  2.67it/s]

'feels_like' Imputation Summary (No Context):
 - Imputed values: 858
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  14%|█▎        | 5/37 [00:01<00:11,  2.73it/s]

'temp_min' Imputation Summary (No Context):
 - Imputed values: 483
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  16%|█▌        | 6/37 [00:02<00:11,  2.73it/s]

'temp_max' Imputation Summary (No Context):
 - Imputed values: 478
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  19%|█▉        | 7/37 [00:02<00:10,  2.79it/s]

'air_pressure' Imputation Summary (No Context):
 - Imputed values: 492
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  22%|██▏       | 8/37 [00:02<00:10,  2.84it/s]

'air_humidity' Imputation Summary (No Context):
 - Imputed values: 858
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  24%|██▍       | 9/37 [00:03<00:09,  2.89it/s]

'wind_speed' Imputation Summary (No Context):
 - Imputed values: 488
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  27%|██▋       | 10/37 [00:03<00:09,  2.97it/s]

'wind_deg' Imputation Summary (No Context):
 - Imputed values: 858
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  30%|██▉       | 11/37 [00:03<00:08,  3.00it/s]

'clouds_sky' Imputation Summary (No Context):
 - Imputed values: 858
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  32%|███▏      | 12/37 [00:04<00:08,  3.02it/s]

'time_encoded' Imputation Summary (No Context):
 - Imputed values: 195
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  35%|███▌      | 13/37 [00:04<00:07,  3.11it/s]

'suicide_day' Imputation Summary (No Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  38%|███▊      | 14/37 [00:04<00:07,  3.14it/s]

'suicide_month' Imputation Summary (No Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  41%|████      | 15/37 [00:05<00:06,  3.16it/s]

'suicide_year' Imputation Summary (No Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  43%|████▎     | 16/37 [00:05<00:06,  3.23it/s]

'suicide_week' Imputation Summary (No Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  46%|████▌     | 17/37 [00:05<00:06,  3.26it/s]

'age_group_encoded' Imputation Summary (No Context):
 - Imputed values: 120
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  49%|████▊     | 18/37 [00:06<00:05,  3.31it/s]

'financial_condition_encoded' Imputation Summary (No Context):
 - Imputed values: 736
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  51%|█████▏    | 19/37 [00:06<00:05,  3.37it/s]

'weather_main_encoded' Imputation Summary (No Context):
 - Imputed values: 857
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  54%|█████▍    | 20/37 [00:06<00:05,  3.25it/s]

'suicide_weekday_encoded' Imputation Summary (No Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  57%|█████▋    | 21/37 [00:07<00:05,  2.89it/s]

'profession_group_encoded' Imputation Summary (No Context):
 - Imputed values: 306
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  59%|█████▉    | 22/37 [00:07<00:05,  2.70it/s]

'hometown_encoded' Imputation Summary (No Context):
 - Imputed values: 27
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  62%|██████▏   | 23/37 [00:07<00:05,  2.75it/s]

'reason_encoded' Imputation Summary (No Context):
 - Imputed values: 272
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  65%|██████▍   | 24/37 [00:08<00:04,  2.79it/s]

'method_encoded' Imputation Summary (No Context):
 - Imputed values: 47
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  68%|██████▊   | 25/37 [00:08<00:04,  2.69it/s]

'weather_description_encoded' Imputation Summary (No Context):
 - Imputed values: 857
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  70%|███████   | 26/37 [00:08<00:03,  2.84it/s]

'marital_status_encoded' Imputation Summary (No Context):
 - Imputed values: 387
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  73%|███████▎  | 27/37 [00:09<00:03,  2.97it/s]

'gender_encoded_female' Imputation Summary (No Context):
 - Imputed values: 7
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  76%|███████▌  | 28/37 [00:09<00:02,  3.26it/s]

'gender_encoded_male' Imputation Summary (No Context):
 - Imputed values: 7
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  81%|████████  | 30/37 [00:09<00:01,  3.96it/s]

'gender_encoded_third gender' Imputation Summary (No Context):
 - Imputed values: 7
 - Skipped (no predictors): 0
 - Errors: 0

'workplace_encoded_rural' Imputation Summary (No Context):
 - Imputed values: 613
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation:  86%|████████▋ | 32/37 [00:10<00:01,  4.96it/s]

'workplace_encoded_semi-urban' Imputation Summary (No Context):
 - Imputed values: 613
 - Skipped (no predictors): 0
 - Errors: 0

'workplace_encoded_urban' Imputation Summary (No Context):
 - Imputed values: 613
 - Skipped (no predictors): 0
 - Errors: 0

'religion_encoded_buddhist' Imputation Summary (No Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

'religion_encoded_christian' Imputation Summary (No Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

'religion_encoded_hindu' Imputation Summary (No Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

'religion_encoded_indigenous' Imputation Summary (No Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

KNN No-Context Imputation: 100%|██████████| 37/37 [00:10<00:00,  3.61it/s]

'religion_encoded_muslim' Imputation Summary (No Context):
 - Imputed values: 39
 - Skipped (no predictors): 0
 - Errors: 0

In [72]:
missing_data_report(df_imputed_knn_no_context)

Group 1: Columns with >70% missing data
Empty DataFrame
Columns: [Column, Missing %, Data Type]
Index: []

Group 2: Columns with >40% to ≤70% missing data
Empty DataFrame
Columns: [Column, Missing %, Data Type]
Index: []

Group 3: Columns with >20% to ≤40% missing data
Empty DataFrame
Columns: [Column, Missing %, Data Type]
Index: []

Group 4: Columns with ≤20% missing data
                      Column  Missing % Data Type
                         age        0.0   float64
                    latitude        0.0   float64
                   longitude        0.0   float64
                  feels_like        0.0   float64
                    temp_min        0.0   float64
                    temp_max        0.0   float64
                air_pressure        0.0   float64
                air_humidity        0.0   float64
                  wind_speed        0.0   float64
                    wind_deg        0.0   float64
                  clouds_sky        0.0   float64
                time_encoded        0.0   float64
                 suicide_day        0.0   float64
               suicide_month        0.0   float64
                suicide_year        0.0   float64
                suicide_week        0.0   float64
           age_group_encoded        0.0   float64
 financial_condition_encoded        0.0   float64
        weather_main_encoded        0.0   float64
     suicide_weekday_encoded        0.0   float64
    profession_group_encoded        0.0   float64
            hometown_encoded        0.0   float64
              reason_encoded        0.0   float64
              method_encoded        0.0   float64
 weather_description_encoded        0.0   float64
      marital_status_encoded        0.0   float64
       gender_encoded_female        0.0   float64
         gender_encoded_male        0.0   float64
 gender_encoded_third gender        0.0   float64
     workplace_encoded_rural        0.0   float64
workplace_encoded_semi-urban        0.0   float64
     workplace_encoded_urban        0.0   float64
   religion_encoded_buddhist        0.0   float64
  religion_encoded_christian        0.0   float64
      religion_encoded_hindu        0.0   float64
 religion_encoded_indigenous        0.0   float64
     religion_encoded_muslim        0.0   float64

## After imputation processing

In [73]:
import numpy as np

# Define one-hot groups
one_hot_groups = {
    'gender': [
        'gender_encoded_female',
        'gender_encoded_male',
        'gender_encoded_third gender'
    ],
    'workplace': [
        'workplace_encoded_rural',
        'workplace_encoded_semi-urban',
        'workplace_encoded_urban'
    ],
    'religion': [
        'religion_encoded_buddhist',
        'religion_encoded_christian',
        'religion_encoded_hindu',
        'religion_encoded_indigenous',
        'religion_encoded_muslim'
    ]
}

# Function to fix one-hot encoding
def fix_one_hot_group(df, columns):
    data = df[columns].to_numpy()
    max_indices = np.argmax(data, axis=1)  # index of max value in each row

    # Set the max column to 1, others to 0
    fixed_data = np.zeros_like(data)
    fixed_data[np.arange(data.shape[0]), max_indices] = 1

    df[columns] = fixed_data
    return df

### fixing one hot columns for context data

In [74]:
# Apply fix to each group
for group_cols in one_hot_groups.values():
    df_imputed_knn_context = fix_one_hot_group(df_imputed_knn_context, group_cols)

### fixing one hot columns for no context data

In [75]:
# Apply fix to each group
for group_cols in one_hot_groups.values():
    df_imputed_knn_no_context = fix_one_hot_group(df_imputed_knn_no_context, group_cols)

In [76]:
# Define your constraints
ordinal_constraints = {
    'suicide_weekday_encoded': (0, 6),
    'age_group_encoded': (0, 6),
    'financial_condition_encoded': (0, 4),
    'weather_main_encoded': (0, 7),
}

## fixing ordinal columns for context data

In [77]:
# Apply rounding and clip to valid range
for col, (low, high) in ordinal_constraints.items():
    if col in df_imputed_knn_context.columns:
        df_imputed_knn_context[col] = df_imputed_knn_context[col].round().clip(lower=low, upper=high)

## fixing ordinal columns for no context data

In [78]:
# Apply rounding and clip to valid range
for col, (low, high) in ordinal_constraints.items():
    if col in df_imputed_knn_context.columns:
        df_imputed_knn_no_context[col] = df_imputed_knn_no_context[col].round().clip(lower=low, upper=high)

In [79]:
df_imputed_knn_context.tail(5)

,age,latitude,longitude,feels_like,temp_min,temp_max,air_pressure,air_humidity,wind_speed,wind_deg,...,gender_encoded_male,gender_encoded_third gender,workplace_encoded_rural,workplace_encoded_semi-urban,workplace_encoded_urban,religion_encoded_buddhist,religion_encoded_christian,religion_encoded_hindu,religion_encoded_indigenous,religion_encoded_muslim
1612,15.0,23.894376,90.166603,300.650,299.922,300.216,1004.6,82.0,3.000,138.6,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1613,27.0,24.309447,88.987565,300.650,299.288,299.288,1003.4,86.2,3.000,135.8,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1614,9.0,23.409802,89.384499,300.650,299.944,299.944,1002.4,86.6,3.726,142.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1615,24.0,23.898795,89.129554,291.776,12.500,23.700,1019.0,77.4,8.000,94.2,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1616,26.0,22.655478,89.794181,291.544,29.800,36.600,1003.8,78.6,3.800,84.6,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [80]:
df_imputed_knn_no_context.tail(5)

,age,latitude,longitude,feels_like,temp_min,temp_max,air_pressure,air_humidity,wind_speed,wind_deg,...,gender_encoded_male,gender_encoded_third gender,workplace_encoded_rural,workplace_encoded_semi-urban,workplace_encoded_urban,religion_encoded_buddhist,religion_encoded_christian,religion_encoded_hindu,religion_encoded_indigenous,religion_encoded_muslim
1612,15.0,23.894376,90.166603,300.650,299.922,300.216,1004.6,82.0,3.000,138.6,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1613,27.0,24.309447,88.987565,300.650,299.288,299.288,1003.4,86.2,3.000,135.8,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1614,9.0,23.409802,89.384499,300.650,299.944,299.944,1002.4,86.6,3.726,142.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1615,24.0,23.898795,89.129554,291.776,12.500,23.700,1019.0,77.4,8.000,94.2,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1616,26.0,22.655478,89.794181,291.544,29.800,36.600,1003.8,78.6,3.800,84.6,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [83]:
# # prompt: give me the code make the latest df downloadable and download that db named final_suicide_cleaned.xlsx ins excel format

# # Make the latest DataFrame downloadable
# from google.colab import files

# # Specify the filename for the Excel file
# filename1 = '8_knn_context.xlsx'

# # Save the DataFrame to an Excel file
# df_imputed_knn_context.to_excel(filename1, index=False)

# # Download the file
# files.download(filename1)

In [84]:
# # prompt: give me the code make the latest df downloadable and download that db named final_suicide_cleaned.xlsx ins excel format

# # Make the latest DataFrame downloadable
# from google.colab import files

# # Specify the filename for the Excel file
# filename2 = '9_knn_no_context.xlsx'

# # Save the DataFrame to an Excel file
# df_imputed_knn_no_context.to_excel(filename2, index=False)

# # Download the file
# files.download(filename2)